import React from 'react';
import './globals.css';

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by AI Studio',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        {children}
      </body>
    </html>
  );
}
