import './globals.css';

import type { ReactNode } from 'react';
import { ForegroundNotificationListener } from '../services/notifications/ForegroundNotificationListener';

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by AI Studio',
  icons: {
    icon: '/dealit-logo.svg',
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <ForegroundNotificationListener />
        {children}
      </body>
    </html>
  );
}
